In [3]:
import pandas as pd
import numpy as np

# 目標 : 分析會員人數分佈，對不同區域會員的年齡分層，並觀察購買金額

In [4]:
members = pd.read_csv('NTU_1317_Member.txt',header = 0,sep = "\t")

C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (10,14) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
members

,ShopId,MemberId,Recency,Frequency,Monetary,Birthday,GenderTypeDef,LocationCity,LocationState,LocationCountry,...,AnnualIncomeTypeDef,RegisterDateTime,RegisterSourceTypeDef,ValidFlag,MinOrderDate,MaxOrderDate,IsAppInstalled,IsInBlackList,MinAppOpenDateTime,MaxAppOpenDateTime
0,1317,88812F54-9F19-49C0-BC77-86065C356D26,251,3,4011.0,1980-08-08,Female,NaN,台中市,台灣,...,NaN,2015-09-18 19:18:48.050,iOSApp,1,2015-09-18,2017-05-02,有,NaN,2015-09-18 18:45:35.707,2017-07-30 21:30:34.940
1,1317,AB3232A1-03C6-4425-8062-EEECB633FB5A,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-03-13 01:11:05.403,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
2,1317,CC63B70D-CD6D-4538-BDDE-4B293F95A654,659,1,529.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-03-20 02:20:35.493,Web,1,2016-03-20,2016-03-20,NaN,NaN,NaN,NaN
3,1317,17ED6C4D-0B91-4EB4-9992-117E9440425D,56,3,2438.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-06-02 22:16:47.363,Web,1,2017-06-02,2017-10-27,NaN,NaN,NaN,NaN
4,1317,1BA9F6E3-67FD-4AAF-8011-2CBEA98B4828,717,1,550.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-01-22 14:46:30.040,Web,1,2016-01-22,2016-01-22,有,NaN,2016-01-22 14:50:32.173,2017-02-21 05:51:05.080
5,1317,E697E909-3142-4686-A7C6-540909465169,13,3,2651.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2015-10-01 20:13:05.657,Web,1,2015-10-01,2015-10-16,NaN,NaN,NaN,NaN
6,1317,93FC0272-134F-48FF-8678-AD4A4DBB5069,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-02-24 08:51:00.343,AndroidApp,1,1900-01-01,NaN,有,NaN,2017-02-24 08:50:14.220,2017-02-28 05:47:26.317
7,1317,D8A55D64-AEB0-4DC4-85C6-3372238C46D3,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-03-19 13:13:10.527,Web,1,2017-03-19,2017-03-19,NaN,NaN,NaN,NaN
8,1317,978EBCAE-9E66-44D9-926B-D35B0C1079E9,190,1,1174.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-07-02 10:58:30.220,Web,1,2017-07-02,2017-07-02,NaN,NaN,NaN,NaN
9,1317,761C39F9-CDA6-44E2-AFA8-7A1CAA037573,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-04-25 21:46:57.683,Web,1,2016-12-29,2016-12-29,NaN,NaN,NaN,NaN
10,1317,78FB737B-5BD4-48BD-8A4F-E39E6F2E7DB5,-1,0,0.0,1990-06-22,Female,NaN,新竹市,台灣,...,NaN,2016-02-15 23:01:52.577,AndroidApp,1,1900-01-01,NaN,有,NaN,2016-02-15 23:01:14.760,2016-08-23 23:11:20.197
11,1317,A8E7F918-8B05-422E-A9F9-F4972E1186E0,165,2,2508.0,1986-07-15,Female,NaN,台北市,台灣,...,NaN,2017-04-30 20:43:30.083,Web,1,2017-05-01,2017-07-27,有,NaN,2017-04-30 23:13:29.093,2017-08-30 00:02:57.377
12,1317,7A3C8291-59AC-47C2-A22B-64AFC324619B,36,9,13489.0,1987-01-21,Female,NaN,高雄市,台灣,...,NaN,2016-09-04 23:42:52.570,AndroidApp,1,2016-09-04,2017-08-05,有,NaN,2016-09-01 15:21:25.957,2017-07-14 07:02:36.593
13,1317,52B48400-EB1B-4797-9430-52C7398E28D2,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-12-21 20:59:40.597,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
14,1317,059EE4B4-13A3-471D-80F1-AD897227E8A2,-1,0,0.0,1998-09-11,Female,NaN,新竹縣,台灣,...,NaN,2016-08-15 12:42:45.033,Web,1,1900-01-01,NaN,有,NaN,2016-10-04 23:04:41.330,2016-12-04 05:45:43.153
15,1317,FE0428CE-1DDE-4419-9B0F-459BE501C855,481,1,693.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-09-14 10:41:32.337,Web,1,2016-09-14,2016-09-14,NaN,NaN,NaN,NaN
16,1317,84152EFC-EE1C-4E31-AA8A-B86E6B9B5A73,588,1,747.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-05-29 23:34:45.587,Web,1,2016-05-30,2016-05-30,有,NaN,2016-05-29 23:56:10.310,2016-06-14 12:27:49.917
17,1317,ECCC9C73-E4B5-4052-9688-1CE4EC33D086,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-12-02 16:36:43.387,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
18,1317,B3E3DE19-15AE-42ED-91FB-19E18177531A,359,1,2108.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-01-14 20:37:40.677,Web,1,2017-01-14,2017-01-14,有,NaN,2017-01-30 17:53:11.957,2017-04-11 05:44:45.480
19,1317,A1A54713-CB23-4BC0-BA10-C2430CCF11B0,649,1,948.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-03-30 19:51:50.397,Web,1,2016-03-30,2016-03-30,NaN,NaN,NaN,NaN
20,1317,9E2F2520-D00C-4759-BC8F-0A50828D69F5,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-05-15 00:40:41.763,Web,1,2016-05-17,2016-05-17,有,NaN,2016-05-18 16:27:14.167,2016-05-22 05:50:26.350
21,1317,CFD48B12-770D-4AE8-BCF5-1543C8242320,273,2,2774.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-10-18 00:52:11.473,Web,1,2016-10-18,2017-04-10,NaN,NaN,NaN,NaN
22,1317,2B73AC64-4794-4676-8954-337131A2A666,467,1,783.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-09-28 11:14:10.760,Web,1,2016-09-28,2016-09-28,NaN,NaN,NaN,NaN
23,1317,930A7AF9-2D4D-49D2-8BF9-6B8E0D40B1EC,-1,0,0.0,1999-01-28,Female,NaN,彰化縣,台灣,...,NaN,2017-08-13 17:36:40.113,Web,1,1900-01-01,NaN,有,NaN,2017-09-03 01:09:50.880,2017-09-05 05:56:07.987
24,1317,B8319921-51D5-4E62-A4D6-E1A6C1D99C0F,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-04-21 00:15:12.927,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
25,1317,44DFCAC0-B57B-440C-904A-85E7F14DE034,180,1,1230.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-07-12 21:56:51.550,Web,1,2017-07-12,2017-07-12,NaN,NaN,NaN,NaN
26,1317,A050C9FB-E2D7-449D-919F-2151DEED2223,59,1,730.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-11-10 21:22:57.937,Web,1,2017-11-10,2017-11-10,NaN,NaN,NaN,NaN
27,1317,1B8E29C1-3A88-43E4-989B-5046BC3676AB,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-12-10 13:41:19.250,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
28,1317,EACC5339-0CA9-4724-BC14-D7FBFB0AF486,-1,0,0.0,1998-09-19,Female,NaN,桃園市,台灣,...,NaN,2016-04-18 07:54:16.560,iOSApp,1,1900-01-01,NaN,有,NaN,2016-04-18 07:53:36.037,2016-12-06 05:44:45.527
29,1317,858F8540-153D-46CB-8E22-16590FE085B6,93,3,752.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-07-23 21:52:24.887,Web,1,2016-07-23,2016-07-27,有,NaN,2016-07-23 21:54:27.030,2016-09-02 14:40:30.067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815762,1317,058E1695-322B-4D26-9597-A02741C5F3D6,824,2,1724.0,1994-05-08,Female,NaN,新北市,台灣,...,NaN,2015-07-23 18:30:36.873,NaN,1,2015-07-23,2015-10-07,有,NaN,2015-07-21 12:18:14.223,2016-06-01 05:47:10.960
815763,1317,6788BB6D-51D6-4887-9453-8FCADB787AA8,887,1,849.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2015-08-05 13:56:59.967,Web,1,2015-08-05,2015-08-05,NaN,NaN,NaN,NaN
815764,1317,AEF56674-4668-418E-BD82-FB9AE88DE893,131,4,1169.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-06-03 12:58:37.823,Web,1,2017-06-03,2017-08-30,有,NaN,2017-02-25 10:45:16.197,2017-10-23 02:44:46.330
815765,1317,93000A27-9249-42DC-8157-33139326E096,257,1,859.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-08-11 23:03:56.713,Web,1,2017-04-24,2017-04-26,NaN,NaN,NaN,NaN
815766,1317,076A9D5B-6FF9-447B-893E-E8FB77BF751F,206,1,1083.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-06-16 15:57:24.407,Web,1,2017-06-16,2017-06-16,NaN,NaN,NaN,NaN
815767,1317,88F329D3-0F8D-4D3E-B731-98548E7F2FFF,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2015-08-09 23:38:23.040,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
815768,1317,FE085DA9-35E4-4334-8825-2AC04ED9318E,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2015-11-07 21:34:11.513,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
815769,1317,24ACCA37-644E-4EAC-8222-067EBAC67DE9,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2015-09-14 21:21:02.167,iOSApp,1,1900-01-01,NaN,有,NaN,2015-08-25 22:52:38.333,2015-10-18 05:42:27.870
815770,1317,D4C74F24-108A-4175-A351-08CC96F266B7,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-12-01 23:45:10.767,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
815771,1317,44E7E070-5E74-4C41-88A1-CF2BB1AE9097,10,2,2545.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-01-03 00:47:44.483,AndroidApp,1,2017-03-18,2017-12-29,有,NaN,2017-01-03 00:47:27.453,2018-01-08 21:27:20.053
815772,1317,2508310F-84EC-40CD-B8D6-E4CB6D5AB777,787,1,1013.0,1982-05-24,Female,NaN,桃園市,台灣,...,NaN,2015-11-13 03:09:07.757,AndroidApp,1,2015-11-13,2015-11-13,有,NaN,2015-11-13 02:40:50.340,2017-03-21 02:25:56.640
815773,1317,1640147E-DF73-4E0A-977E-74B79FBAAAAA,268,1,199.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2015-08-26 22:41:29.520,Web,1,2016-11-09,2017-04-15,NaN,NaN,NaN,NaN
815774,1317,B789B39F-9379-49C3-9A94-A56210E2D106,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2015-08-23 14:46:00.660,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
815775,1317,28CAFE1C-B4D7-49BB-8950-7947A6233D47,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-07-13 20:47:42.737,Web,1,2016-07-13,2016-07-13,NaN,NaN,NaN,NaN
815776,1317,732CA049-DA27-46DE-82C1-AB8D8FC1E4F4,371,1,1038.0,1987-04-25,Female,NaN,高雄市,台灣,...,NaN,2017-01-01 20:01:40.167,AndroidApp,1,2017-01-02,2017-01-02,有,NaN,2016-12-31 21:37:26.257,2017-08-08 05:55:08.290
815777,1317,7838D9E6-6DBC-42D9-B6CA-DEADAA38340C,374,2,3224.0,1982-01-25,Female,NaN,台中市,台灣,...,NaN,2016-12-08 06:32:42.147,iOSApp,1,2016-12-08,2016-12-30,有,NaN,2016-12-08 06:32:02.757,2017-04-30 05:55:15.800
815778,1317,DD5269CD-290C-4A62-9CF7-65A99766B2F8,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-11-04 20:01:44.493,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
815779,1317,F92FF0B9-E47E-46E9-BB11-84C35912C95A,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-09-28 19:12:52.667,AndroidApp,1,1900-01-01,NaN,有,NaN,2016-09-28 19:11:34.127,2017-03-05 05:45:01.793
815780,1317,2E7C7DA0-45DE-49D0-B9BA-54A99BA0DE83,613,1,1443.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-05-05 01:51:28.403,Web,1,2016-05-05,2016-05-05,NaN,NaN,NaN,NaN
815781,1317,8FDA7650-DD8F-4E15-9780-753DA8D3DCA4,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-09-04 19:47:22.137,Web,1,2017-09-04,2017-09-04,NaN,NaN,NaN,NaN
815782,1317,DF3F5E18-AF03-49CD-995A-4E9082E53C06,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-10-24 22:06:40.023,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
815783,1317,C99381CA-6D33-492D-87B4-9AE83CBE4FE0,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-06-15 18:21:51.653,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
815784,1317,10CA861B-5EAD-4FF4-A196-F384EC1F3C9F,217,3,3243.0,1985-05-08,Female,NaN,台南市,NaN,...,NaN,2016-10-02 00:50:06.620,Web,1,2016-10-02,2017-06-05,有,NaN,2016-11-11 22:52:15.430,2017-05-12 10:29:57.830
815785,1317,21CA76FE-FCD5-4880-85A4-5864DEE9CF9B,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2015-11-28 00:30:18.397,iOSApp,1,1900-01-01,NaN,有,NaN,2015-11-25 02:23:33.473,2016-01-17 18:49:47.473
815786,1317,F4035CDB-008B-4078-827F-035C4FD05174,599,2,1115.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-03-17 10:56:44.957,Web,1,2016-03-17,2016-05-19,NaN,NaN,NaN,NaN
815787,1317,A13E0AB8-5276-4FDA-AA06-CB5EACE64E0B,292,1,1166.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-03-22 17:19:27.327,Web,1,2017-03-22,2017-03-22,NaN,NaN,NaN,NaN
815788,1317,0BF15A9B-85A1-4C38-A13A-97BEDE0DA0D2,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-11-25 11:40:55.257,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
815789,1317,AF7B3E91-0E31-40A7-B96A-29BEF7DE3255,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2016-07-01 23:09:46.943,Web,1,1900-01-01,NaN,NaN,NaN,NaN,NaN
815790,1317,D98A03B6-0E96-48B3-AF07-0FD5DEBF4F62,-1,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2017-07-12 10:54:12.313,AndroidApp,1,1900-01-01,NaN,有,NaN,2017-07-11 19:21:18.100,2017-07-30 05:57:34.527
815791,1317,A432F3E3-831E-4DA1-9B74-1003EC9630A6,-1,0,0.0,1995-09-03,Female,NaN,臺中市,臺灣,...,NaN,2015-11-04 09:20:10.070,Web,1,2015-11-05,2015-11-05,有,NaN,2015-11-04 22:13:38.233,2015-11-17 05:40:18.577

## 有發現到縣市填寫不完全/亂填，建議註冊會員時用表單方式

In [6]:
dict_region = {"北部":['臺北','台北','新北','基隆','宜蘭','桃園','新竹'],
               "中部":['苗栗','臺中','台中','彰化','南投','雲林'],
               "南部":['嘉義','臺南','台南','高雄','屏東','澎湖'],
               "東部":['花蓮','台東','臺東']
              }

In [7]:
m_state = members[members['LocationState'] == members['LocationState']]  #過濾nan
m_state

,ShopId,MemberId,Recency,Frequency,Monetary,Birthday,GenderTypeDef,LocationCity,LocationState,LocationCountry,...,AnnualIncomeTypeDef,RegisterDateTime,RegisterSourceTypeDef,ValidFlag,MinOrderDate,MaxOrderDate,IsAppInstalled,IsInBlackList,MinAppOpenDateTime,MaxAppOpenDateTime
0,1317,88812F54-9F19-49C0-BC77-86065C356D26,251,3,4011.0,1980-08-08,Female,NaN,台中市,台灣,...,NaN,2015-09-18 19:18:48.050,iOSApp,1,2015-09-18,2017-05-02,有,NaN,2015-09-18 18:45:35.707,2017-07-30 21:30:34.940
10,1317,78FB737B-5BD4-48BD-8A4F-E39E6F2E7DB5,-1,0,0.0,1990-06-22,Female,NaN,新竹市,台灣,...,NaN,2016-02-15 23:01:52.577,AndroidApp,1,1900-01-01,NaN,有,NaN,2016-02-15 23:01:14.760,2016-08-23 23:11:20.197
11,1317,A8E7F918-8B05-422E-A9F9-F4972E1186E0,165,2,2508.0,1986-07-15,Female,NaN,台北市,台灣,...,NaN,2017-04-30 20:43:30.083,Web,1,2017-05-01,2017-07-27,有,NaN,2017-04-30 23:13:29.093,2017-08-30 00:02:57.377
12,1317,7A3C8291-59AC-47C2-A22B-64AFC324619B,36,9,13489.0,1987-01-21,Female,NaN,高雄市,台灣,...,NaN,2016-09-04 23:42:52.570,AndroidApp,1,2016-09-04,2017-08-05,有,NaN,2016-09-01 15:21:25.957,2017-07-14 07:02:36.593
14,1317,059EE4B4-13A3-471D-80F1-AD897227E8A2,-1,0,0.0,1998-09-11,Female,NaN,新竹縣,台灣,...,NaN,2016-08-15 12:42:45.033,Web,1,1900-01-01,NaN,有,NaN,2016-10-04 23:04:41.330,2016-12-04 05:45:43.153
23,1317,930A7AF9-2D4D-49D2-8BF9-6B8E0D40B1EC,-1,0,0.0,1999-01-28,Female,NaN,彰化縣,台灣,...,NaN,2017-08-13 17:36:40.113,Web,1,1900-01-01,NaN,有,NaN,2017-09-03 01:09:50.880,2017-09-05 05:56:07.987
28,1317,EACC5339-0CA9-4724-BC14-D7FBFB0AF486,-1,0,0.0,1998-09-19,Female,NaN,桃園市,台灣,...,NaN,2016-04-18 07:54:16.560,iOSApp,1,1900-01-01,NaN,有,NaN,2016-04-18 07:53:36.037,2016-12-06 05:44:45.527
35,1317,D2C4288E-733B-4487-8D09-E5F7189332B2,759,3,2867.0,1979-02-18,Female,NaN,台中市,台灣,...,NaN,2015-10-13 16:51:07.783,AndroidApp,1,2015-10-16,2015-12-11,有,NaN,2015-10-13 16:49:15.177,2016-02-18 00:45:12.773
36,1317,FA444442-35FF-488B-A0E9-625863DBC3C7,755,1,689.0,1988-06-23,Female,NaN,苗栗縣,台灣,...,NaN,2015-11-19 23:26:20.070,iOSApp,1,2015-12-15,2015-12-15,有,NaN,2015-11-19 23:24:57.813,2017-07-25 05:44:17.863
39,1317,023B2D1C-2CD8-4AB9-91E2-38FB96CF08D3,396,3,4770.0,1998-01-06,Female,NaN,桃園市,台灣,...,NaN,2015-12-10 00:30:34.497,Web,1,2016-10-21,2016-12-08,有,NaN,2015-12-11 17:37:42.847,2016-12-13 14:38:05.013
45,1317,9B991146-15BF-4816-AE64-56ED8BFCCA0E,239,1,948.0,1987-06-14,Female,NaN,台北市,台灣,...,NaN,2017-05-14 13:29:17.290,iOSApp,1,2017-05-14,2017-05-14,有,NaN,2017-04-23 21:09:39.713,2017-05-14 13:29:17.343
52,1317,5943421C-8CEC-451F-AF26-5A3BB8FFD652,440,5,9935.0,1986-04-25,Female,NaN,台中市,台灣,...,NaN,2015-07-14 16:37:22.213,NaN,1,2015-06-30,2016-10-25,有,NaN,2015-10-02 13:58:43.203,2016-11-11 05:55:48.607
56,1317,95930BB0-B512-47F0-89A5-A9BB870F010E,57,2,2400.0,1998-11-25,Female,NaN,台中市,台灣,...,NaN,2017-05-13 02:25:12.167,Web,1,2017-05-14,2017-11-12,有,NaN,2017-05-16 12:22:27.307,2017-12-18 03:18:02.290
58,1317,24D3D74A-D12F-40CA-95B0-5AF7625775BB,-1,0,0.0,1997-04-20,Female,NaN,高雄市,台灣,...,NaN,2015-09-28 21:47:50.467,AndroidApp,1,1900-01-01,NaN,有,NaN,2015-09-27 09:28:51.293,2017-09-26 05:45:12.693
75,1317,D0137A57-02CF-4CD8-842A-EE6C2C55FC03,284,6,4088.0,1993-08-15,Female,NaN,桃園市,台灣,...,NaN,2016-04-26 14:07:30.273,Web,1,2016-04-26,2017-03-30,有,NaN,2016-05-10 06:26:07.137,2017-12-25 11:52:32.337
80,1317,401A0572-2759-4EF0-A7A1-4247708EE954,295,1,685.0,1993-08-08,Female,NaN,桃園市,NaN,...,NaN,2017-03-19 03:54:19.453,Web,1,2017-03-19,2017-03-19,NaN,NaN,NaN,NaN
84,1317,81D1B632-4B39-4E2D-A470-BB315C435D5B,23,1,2920.0,1993-04-01,Female,NaN,新竹市,NaN,...,NaN,2017-10-08 22:22:06.060,Web,1,2017-12-16,2017-12-16,NaN,NaN,NaN,NaN
89,1317,8AE7AED8-8FC3-41E8-8AFB-65300EB94EA4,-1,0,0.0,1995-10-20,Female,NaN,宜蘭,台灣,...,NaN,2015-11-18 13:26:03.963,AndroidApp,1,2015-11-19,2015-11-19,有,NaN,2015-11-18 12:14:59.297,2016-01-03 05:40:41.267
90,1317,CE444CE5-0329-4B53-8AE6-5F899BB68F7D,-1,0,0.0,1990-12-09,Female,NaN,台中市,台灣,...,NaN,2015-07-16 00:39:42.987,NaN,1,1900-01-01,NaN,有,NaN,2015-07-16 00:34:19.030,2018-01-09 01:24:56.860
93,1317,547A3DE8-8DCD-44A2-B0A0-9DC36AB7954D,-1,0,0.0,1998-11-10,Female,NaN,台北市,台灣,...,NaN,2016-10-07 13:37:12.167,iOSApp,1,1900-01-01,NaN,有,NaN,2016-10-07 13:36:58.833,2016-10-11 05:51:37.773
96,1317,6FA15899-BA2E-4DF7-B344-0881197AD828,537,4,2888.0,1992-07-20,Female,NaN,桃園市,台灣,...,NaN,2015-09-22 21:47:09.787,Web,1,2015-09-22,2016-07-20,有,NaN,2015-12-29 21:22:29.823,2016-10-25 05:47:51.787
103,1317,BD97A714-667E-462D-B544-B853047D9F08,469,6,8218.0,1982-03-08,Female,NaN,桃園市,台灣,...,NaN,2016-01-27 22:38:05.133,AndroidApp,1,2016-03-04,2016-09-26,有,NaN,2016-01-19 22:35:42.047,2017-04-30 05:54:46.583
109,1317,68871BC4-C8A6-4626-9168-E0DC4386BFB4,500,4,4630.0,1983-01-02,Female,NaN,台北市,NaN,...,NaN,2016-06-02 22:45:33.450,Web,1,2016-06-02,2016-08-26,有,NaN,2016-06-07 14:51:54.517,2017-09-10 05:57:02.630
115,1317,A530F15F-35E4-4C3D-8C78-FEC221CF2854,150,1,345.0,1992-07-28,Female,NaN,新北市,台灣,...,NaN,2017-08-11 12:39:41.903,Web,1,2017-08-11,2017-08-11,有,NaN,2017-08-13 07:01:51.547,2017-08-13 07:02:23.263
118,1317,4F1BC4E7-C3DD-4FD6-843C-116FF57060FB,12,1,678.0,1982-06-21,Female,NaN,新北市,NaN,...,NaN,2017-08-25 01:20:26.913,Web,1,2017-12-27,2017-12-27,NaN,NaN,NaN,NaN
119,1317,789E50BB-7456-4A95-B72E-F6EB3E2A2811,293,1,449.0,1990-05-10,Female,NaN,台中市,台灣,...,NaN,2017-03-21 14:11:36.087,Web,1,2017-03-21,2017-03-21,有,NaN,2017-03-21 14:13:25.117,2018-01-07 10:41:40.160
120,1317,36AA9928-F0C6-4987-B806-368D0380EF13,525,1,547.0,1993-08-23,Female,NaN,高雄市,台灣,...,NaN,2016-08-01 11:37:33.703,iOSApp,1,2016-08-01,2016-08-01,有,NaN,2016-07-31 23:15:28.310,2017-06-07 05:54:56.873
122,1317,2D58E28E-CC3B-4BA5-9E72-AE6F4036EE29,335,2,2169.0,1989-10-05,Female,NaN,台南市,台灣,...,NaN,2016-03-09 11:18:48.537,Web,1,2016-03-09,2017-02-07,有,NaN,2017-02-07 09:18:43.750,2017-04-23 15:32:43.873
123,1317,04CB90D7-0E10-46C1-BB7E-2E56FE1D8662,102,2,2468.0,1995-08-10,Female,NaN,新北市,台灣,...,NaN,2017-07-12 11:49:27.010,Web,1,2017-07-12,2017-09-16,有,NaN,2017-09-20 00:24:03.163,2017-11-26 02:09:14.350
125,1317,EE4988EA-EFA4-4F3E-B0EE-F7EFECA9A701,236,2,2694.0,1992-03-13,Female,NaN,新北市,台灣,...,NaN,2016-02-09 16:35:25.567,iOSApp,1,2016-02-09,2017-05-17,有,NaN,2016-01-20 23:18:27.993,2017-05-08 23:45:11.067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815645,1317,7BA4BC5B-C898-49D9-B7A7-C2D9F5FB5D4B,833,1,126.0,1995-10-29,Female,NaN,高雄市,台灣,...,NaN,2015-07-21 15:43:31.790,NaN,1,2015-09-28,2015-09-28,有,NaN,2015-07-21 15:40:54.173,2015-07-25 05:39:09.343
815646,1317,17362D5F-2D75-4101-90A9-46A43A2E95DF,226,1,440.0,1995-08-02,Female,NaN,宜蘭縣,台灣,...,NaN,2016-09-15 20:40:46.457,Web,1,2017-05-27,2017-05-27,有,NaN,2017-05-27 14:45:00.663,2017-09-26 05:45:43.007
815655,1317,6144E596-433D-45D0-9A05-45A21F385E12,185,5,4599.0,1986-08-31,Female,NaN,台南市,台灣,...,NaN,2015-12-05 09:04:16.827,Web,1,2015-12-09,2017-07-07,有,NaN,2015-12-05 09:10:46.053,2017-12-30 01:33:06.293
815657,1317,0CA52CA2-72A4-4A37-B2B1-201A685D982F,749,3,1734.0,1992-09-08,Female,NaN,新北市,台灣,...,NaN,2015-10-11 15:20:08.663,Web,1,2015-10-30,2015-12-21,有,NaN,2015-11-04 13:10:48.033,2016-06-15 05:43:12.140
815663,1317,446B9F78-2D77-4D96-AACB-612864215323,735,1,989.0,1988-09-17,Female,NaN,台中市,台灣,...,NaN,2016-01-04 13:05:34.723,Web,1,2016-01-04,2016-01-04,有,NaN,2016-01-04 22:45:10.533,2017-06-06 05:45:25.870
815668,1317,77A2BC14-BA4B-4E69-B376-A2A6E0C43C4C,533,3,5346.0,1992-05-27,Female,NaN,台北市,台灣,...,NaN,2016-04-04 13:52:09.177,Web,1,2016-04-09,2016-07-24,有,NaN,2016-04-13 22:56:10.560,2016-10-09 05:47:29.587
815671,1317,056CC58F-DA87-4D74-94C7-8FB117281413,722,1,736.0,1988-04-01,Female,NaN,新北市,台灣,...,NaN,2016-01-17 20:53:24.130,Web,1,2016-01-17,2016-01-17,有,NaN,2016-01-19 22:20:09.740,2016-04-05 05:42:17.040
815675,1317,21AAE1A7-F7D1-4BC0-9C5B-257C2A58A12E,-1,0,0.0,1988-10-02,Female,NaN,宜蘭縣,NaN,...,NaN,2016-11-04 17:21:35.980,Web,1,2016-11-04,2016-11-04,有,NaN,2016-11-04 17:26:31.593,2016-11-16 05:50:15.077
815676,1317,3C498C8A-1C14-41F8-989B-680D09409CE5,-1,0,0.0,1986-03-19,Female,NaN,新北市,台灣,...,NaN,2017-11-26 15:22:08.980,iOSApp,1,1900-01-01,NaN,有,NaN,2017-11-26 15:21:44.300,2017-11-26 15:22:09.053
815679,1317,04284E75-D905-4515-9B23-7C51FE24DA5B,241,2,1544.0,1995-08-19,Female,NaN,台南市,台灣,...,NaN,2016-04-23 18:31:37.403,iOSApp,1,2016-05-06,2017-05-12,有,NaN,2016-04-23 02:05:34.817,2017-10-28 09:51:18.747
815681,1317,536D8AB2-4B72-472E-8AF9-1F54D785B512,520,1,1742.0,1983-11-09,Female,NaN,台北市,台灣,...,NaN,2016-08-06 04:09:04.520,iOSApp,1,2016-08-06,2016-08-06,有,NaN,2016-07-15 17:57:24.127,2016-08-06 04:09:04.567
815684,1317,001D8AA0-F4CD-47EF-9DB3-4A09801AED83,-1,0,0.0,1995-09-11,Female,NaN,台中市,台灣,...,NaN,2016-04-01 01:36:29.047,iOSApp,1,2016-04-01,2016-04-01,有,NaN,2016-04-01 01:10:10.020,2016-11-23 10:49:17.447
815685,1317,BCC0A6F8-2BEB-4244-93A8-EA3DD846F96D,415,2,4346.0,1980-12-18,Female,NaN,新北市,台灣,...,NaN,2016-06-30 08:01:52.463,Web,1,2016-09-23,2016-11-19,有,NaN,2016-07-02 03:41:12.097,2017-05-11 00:22:59.397
815686,1317,61FBA99F-AA7D-4DBF-BB7B-C12A1A9185E8,108,4,3233.0,1979-09-30,Female,NaN,台北市,NaN,...,NaN,2016-11-16 15:21:47.893,Web,1,2016-11-16,2017-08-14,NaN,NaN,NaN,NaN
815692,1317,7FF134DB-9B99-4797-B56F-3ACF0DE05C08,547,1,587.0,1989-12-29,Female,NaN,台南市,台灣,...,NaN,2016-07-10 01:05:47.790,AndroidApp,1,2016-07-10,2016-07-10,有,NaN,2016-07-10 01:03:07.453,2016-07-26 05:47:22.187
815696,1317,76BD6746-DAFC-4ADF-82FF-594AC8030F43,-1,0,0.0,2004-01-12,Female,NaN,新竹縣,台灣,...,NaN,2017-06-13 21:35:20.627,AndroidApp,1,1900-01-01,NaN,有,NaN,2017-06-13 21:34:18.647,2017-12-23 22:24:06.377
815705,1317,4ABF36CD-302C-414D-8D3E-1C45C49666BD,243,1,1348.0,1978-04-27,Female,NaN,新竹市,NaN,...,NaN,2017-05-09 20:00:29.277,Web,1,2017-05-10,2017-06-02,NaN,NaN,NaN,NaN
815712,1317,C8E45A6A-9DD0-4F64-87CC-27D63B3969C0,243,1,524.0,1982-12-18,Female,NaN,桃園市,台灣,...,NaN,2016-07-19 15:44:13.177,Web,1,2016-07-19,2017-05-10,有,NaN,2017-05-10 23:14:27.073,2017-12-29 17:14:53.797
815713,1317,2531A58E-2AF0-4E14-A69E-BA47BA2F2E92,74,3,3608.0,1984-05-11,Female,NaN,台北市,NaN,...,NaN,2017-06-04 03:30:38.653,Web,1,2017-08-13,2017-08-17,NaN,NaN,NaN,NaN
815734,1317,C0E1896D-10A6-41C2-8A71-623EAF0EA10A,404,1,1920.0,1980-04-05,Female,NaN,桃園市,台灣,...,NaN,2016-10-22 22:29:15.590,Web,1,2016-11-30,2016-11-30,有,NaN,2016-11-17 12:15:27.570,2017-12-26 05:45:02.243
815740,1317,CAD97000-E639-4686-920F-7D4283F3E919,407,1,2228.0,1987-07-05,Female,NaN,基隆市,台灣,...,NaN,2016-06-22 17:16:45.913,Web,1,2016-11-27,2016-11-27,有,NaN,2016-07-21 18:52:23.090,2017-10-17 12:01:43.563
815741,1317,A5B37452-E6A5-4CFF-AD65-084A06EBFED5,866,3,1781.0,1997-06-28,Female,NaN,高雄市,NaN,...,NaN,2015-07-14 16:37:35.400,NaN,1,2015-07-03,2015-08-26,NaN,NaN,NaN,NaN
815751,1317,BCCFF513-72CB-4C24-AD72-D09956AED6A9,956,1,86.0,1994-08-30,Female,NaN,台南,台灣,...,NaN,2015-06-11 22:07:49.033,NaN,1,2015-05-24,2015-06-06,有,NaN,2015-05-24 00:55:17.647,2015-07-09 05:38:44.750
815754,1317,0DDEFEE6-E03E-4001-A5CF-8C6062DECA07,110,3,3388.0,1992-03-19,Female,NaN,新北市,臺灣,...,NaN,2015-09-07 02:34:48.440,AndroidApp,1,2016-03-16,2016-11-14,有,NaN,2015-09-07 02:30:09.623,2017-12-02 01:29:36.407
815762,1317,058E1695-322B-4D26-9597-A02741C5F3D6,824,2,1724.0,1994-05-08,Female,NaN,新北市,台灣,...,NaN,2015-07-23 18:30:36.873,NaN,1,2015-07-23,2015-10-07,有,NaN,2015-07-21 12:18:14.223,2016-06-01 05:47:10.960
815772,1317,2508310F-84EC-40CD-B8D6-E4CB6D5AB777,787,1,1013.0,1982-05-24,Female,NaN,桃園市,台灣,...,NaN,2015-11-13 03:09:07.757,AndroidApp,1,2015-11-13,2015-11-13,有,NaN,2015-11-13 02:40:50.340,2017-03-21 02:25:56.640
815776,1317,732CA049-DA27-46DE-82C1-AB8D8FC1E4F4,371,1,1038.0,1987-04-25,Female,NaN,高雄市,台灣,...,NaN,2017-01-01 20:01:40.167,AndroidApp,1,2017-01-02,2017-01-02,有,NaN,2016-12-31 21:37:26.257,2017-08-08 05:55:08.290
815777,1317,7838D9E6-6DBC-42D9-B6CA-DEADAA38340C,374,2,3224.0,1982-01-25,Female,NaN,台中市,台灣,...,NaN,2016-12-08 06:32:42.147,iOSApp,1,2016-12-08,2016-12-30,有,NaN,2016-12-08 06:32:02.757,2017-04-30 05:55:15.800
815784,1317,10CA861B-5EAD-4FF4-A196-F384EC1F3C9F,217,3,3243.0,1985-05-08,Female,NaN,台南市,NaN,...,NaN,2016-10-02 00:50:06.620,Web,1,2016-10-02,2017-06-05,有,NaN,2016-11-11 22:52:15.430,2017-05-12 10:29:57.830
815791,1317,A432F3E3-831E-4DA1-9B74-1003EC9630A6,-1,0,0.0,1995-09-03,Female,NaN,臺中市,臺灣,...,NaN,2015-11-04 09:20:10.070,Web,1,2015-11-05,2015-11-05,有,NaN,2015-11-04 22:13:38.233,2015-11-17 05:40:18.577

In [8]:
def get_keys(d, seri_state):
    
    result = list()
    for state in seri_state:
        locate_flag = 0
        for key,value in d.items():
            for a in value:            
                if a in state:
                    result.append(key)
                    locate_flag = 1
                    break
            if locate_flag == 1:
                break
        if locate_flag == 0:
            result.append('not_define')
    return result
    
get_keys(dict_region, ['桃園'])

['北部']

In [9]:
m_state['Area'] = get_keys(dict_region, m_state['LocationState'])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [10]:
m_state =  m_state[m_state['Area'] != 'not_define']

In [11]:
import datetime
today = datetime.date.today()
today.year

m_state['new_Birthday'] = pd.to_datetime(m_state['Birthday'].astype(str), format='%Y-%m-%d', errors='ignore')#濾掉生日亂填的

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [12]:
m_state = m_state[m_state['new_Birthday'] != 'nan']
len(m_state)

206348

In [13]:
a = list(m_state['new_Birthday'])

m_state['age'] = [today.year-datetime.datetime.strptime(a[i],'%Y-%m-%d').year
                  for i in range(len(a))]    
m_state = m_state[(m_state['age']>0) & (m_state['age']<150)]

In [14]:
m_numofarea = pd.DataFrame(m_state.groupby(by = 'Area')['Frequency','Monetary'].sum())
m_numofarea

      Frequency     Monetary
Area
中部       106562  107383737.0
北部       232244  247118421.0
南部       100781   98845343.0
東部         6972    7163608.0

In [15]:
m_numofarea.keys()

Index(['Frequency', 'Monetary'], dtype='object')

In [16]:
for k, v in m_numofarea.items():
    print(v, type(v))

Area
中部    106562
北部    232244
南部    100781
東部      6972
Name: Frequency, dtype: int64 <class 'pandas.core.series.Series'>
Area
中部    107383737.0
北部    247118421.0
南部     98845343.0
東部      7163608.0
Name: Monetary, dtype: float64 <class 'pandas.core.series.Series'>

In [17]:
type(m_numofarea['Frequency'])

pandas.core.series.Series

In [18]:
v.keys()

Index(['中部', '北部', '南部', '東部'], dtype='object', name='Area')

In [19]:
from collections import Counter
c = Counter(m_state['Area'])

m_numofarea['count'] = c.values()
m_numofarea

      Frequency     Monetary   count
Area
中部       106562  107383737.0   49851
北部       232244  247118421.0  104886
南部       100781   98845343.0   48129
東部         6972    7163608.0    3427

In [20]:
import plotly as py

In [21]:
py.tools.set_credentials_file(username='sowhite', api_key='8xNzT8bzXp1CJx7X8GuO')

In [22]:
m_numofarea['totle'] = [0.24666*23572408,0.45313*23572408,0.27048*23572408,0.02326*23572408] #各區域總人口數

In [23]:
m_numofarea

      Frequency     Monetary   count         totle
Area
中部       106562  107383737.0   49851  5.814370e+06
北部       232244  247118421.0  104886  1.068137e+07
南部       100781   98845343.0   48129  6.375865e+06
東部         6972    7163608.0    3427  5.482942e+05

In [24]:
import plotly.graph_objs as go
py.offline.init_notebook_mode(connected=True)
data = [go.Bar(
            x=v.keys(),
            y=m_numofarea['Monetary']/m_numofarea['Frequency']
    )]
layout = go.Layout(
    title='平均每次購買金額',
)
fig = go.Figure(data=data, layout=layout)
py.offline.iplot(fig, filename='平均每次購買金額')

# 可以看出北部每次購買金額高一些，但都差不多在1000左右，可以搭配"滿1500送..."來刺激買氣

In [25]:
fig = {
  "data": [
    {
      "values": m_numofarea['count'],
      "labels": v.keys(),
      "domain": {"x": [0, .48]},
      "name": "members",
      "hoverinfo":"label+percent+name",
      "hole": .4,
      "type": "pie"
    },
      
    {
      "values": m_numofarea['Monetary'],
      "labels":  v.keys(),
      "text":"CO2",
      "textposition":"inside",
      "domain": {"x": [.52, 1]},
      "name": "monetary",
      "hoverinfo":"label+percent+name",
      "hole": .4,
      "type": "pie"
    }],
  "layout": {        
        "annotations": [
            {
                "font": {
                    "size": 20
                },
                "showarrow": False,
                "text": "會員人數分佈",
                "x": 0.16,
                "y": 0.5
            },
            {
                "font": {
                    "size": 20
                },
                "showarrow": False,
                "text": "消費金額分佈",
                "x": 0.83,
                "y": 0.5
            }
            
        ]
    }
}
py.offline.iplot(fig, filename='donut')

# 可以發現北部不只會員人數多，每個人的消費能力也較高

In [26]:
import plotly.graph_objs as go
data = [go.Bar(
            x=v.keys(),
            y=m_numofarea['count']/m_numofarea['totle']
    )]
layout = go.Layout(
    title='占各區人口數之比例',
)
fig = go.Figure(data=data, layout=layout)
py.offline.iplot(fig, filename='平均每次購買金額')

# 北部會員人數最多，密度也最高，代表其他區域接觸到此廠家的資訊較少，
# 比較有發展空間

In [27]:
len(m_state[(m_state['Area']=='中部') & (m_state['age']<20)])

4353

In [28]:
x = v.keys()

trace1 = {
  'x': x,
  'y': [len(m_state[(m_state['Area']=='中部') & (m_state['age']<20)]),
        len(m_state[(m_state['Area']=='北部') & (m_state['age']<20)]),
        len(m_state[(m_state['Area']=='南部') & (m_state['age']<20)]),
        len(m_state[(m_state['Area']=='東部') & (m_state['age']<20)]),
        ],
  'name': '小於20歲',
  'type': 'bar'
};
trace2 = {
  'x': x,
  'y': [len(m_state[(m_state['Area']=='中部') & (m_state['age']>21) & (m_state['age']<40)]),
        len(m_state[(m_state['Area']=='北部') & (m_state['age']>21) & (m_state['age']<40)]),
        len(m_state[(m_state['Area']=='南部') & (m_state['age']>21) & (m_state['age']<40)]),
        len(m_state[(m_state['Area']=='東部') & (m_state['age']>21) & (m_state['age']<40)]),
        ],
  'name': '20-40歲',
  'type': 'bar'
};
trace3 = {
  'x': x,
  'y': [len(m_state[(m_state['Area']=='中部') & (m_state['age']>41) & (m_state['age']<60)]),
        len(m_state[(m_state['Area']=='北部') & (m_state['age']>41) & (m_state['age']<60)]),
        len(m_state[(m_state['Area']=='南部') & (m_state['age']>41) & (m_state['age']<60)]),
        len(m_state[(m_state['Area']=='東部') & (m_state['age']>41) & (m_state['age']<60)]),
        ],
  'name': '40-60歲',
  'type': 'bar'
 }
 
trace4 = {
  'x': x,
  'y': [len(m_state[(m_state['Area']=='中部') & (m_state['age']>61)]),
        len(m_state[(m_state['Area']=='北部') & (m_state['age']>61)]),
        len(m_state[(m_state['Area']=='南部') & (m_state['age']>61)]),
        len(m_state[(m_state['Area']=='東部') & (m_state['age']>61)])],
  'name': '大於60歲',
  'type': 'bar'
 }
 
data = [trace1, trace2, trace3, trace4];
layout = {
  'xaxis': {'title': '地區'},
  'yaxis': {'title': '人數'},
  'barmode':'stack',
  'title': '各區年齡分層與總人數'
};
py.offline.iplot({'data': data, 'layout': layout}, filename='年齡分層')